-- USER SQL
CREATE USER "WITHME" IDENTIFIED BY "5678"  
DEFAULT TABLESPACE "SYSTEM"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "DBA" TO "WITHME" ;
GRANT "CONNECT" TO "WITHME" ;
GRANT "RESOURCE" TO "WITHME" ;

-- SYSTEM PRIVILEGES

-- USERS 테이블 생성
CREATE TABLE USERS 
(
  USER_ID NUMBER NOT NULL 
, POST_ID NUMBER NOT NULL 
, USER_NAME VARCHAR2(20) 
, PASSWORD VARCHAR2(50) NOT NULL 
, FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID)
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    USER_ID 
  )
  ENABLE 
);

-- POSTS 테이블 생성
CREATE TABLE POSTS 
(
  POST_ID NUMBER NOT NULL 
, POST_TITLE VARCHAR2(100) NOT NULL 
, CONTENT VARCHAR2(300) NOT NULL 
, AUTHOR VARCHAR2(30) 
, PASSWORD VARCHAR2(20) NOT NULL 
, CREATE_DATE DATE 
, CONSTRAINT POSTS_PK PRIMARY KEY 
  (
    POST_ID 
  )
  ENABLE 
);

-- COMMENTS 테이블 생성
CREATE TABLE COMMENTS 
(
  COMMENT_ID NUMBER NOT NULL 
, POST_ID NUMBER NOT NULL 
, CONTENT VARCHAR2(200) NOT NULL 
, POST_TITLE VARCHAR2(200) NOT NULL 
, CREATE_DATE DATE 
, PASSWORD VARCHAR2(20) NOT NULL 
, FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID)
, CONSTRAINT COMMENTS_PK PRIMARY KEY 
  (
    COMMENT_ID 
  )
  ENABLE 
);

DROP SEQUENCE POSTSEQ;

-- 시퀀스 생성
CREATE SEQUENCE POSTSEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE SEQUENCE USERSEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE SEQUENCE COMMSEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

SELECT * FROM POSTS ORDER BY post_id;

DELETE FROM POSTS;

INSERT INTO posts (post_id, post_title, content, author, password, create_date)
                 VALUES (POSTSEQ.NEXTVAL, :postTitle, :postContent, :authorName, :password, SYSDATE);
                 
SELECT author, post_title, create_date FROM posts;

SELECT author, content, create_date FROM posts WHERE post_id = :postId;

